// @ts-check
// .nuxt/eslint.config.mjs is generated by `nuxt prepare` via @nuxt/eslint
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Single-word component names are fine for pages/layouts
    'vue/multi-word-component-names': 'off',
    // Prefer const over let where possible
    'prefer-const': 'error',
  },
})
